---
inherit_gem:
  eac_ruby_gem_support: ".rubocop.yml"
Style/StringConcatenation:
  Exclude:
  - lib/eac_ruby_utils/acts_as_immutable/class_methods.rb
  - lib/eac_ruby_utils/envs/base_command/append_command_options.rb
  - lib/eac_ruby_utils/gems_registry/gem.rb
  - lib/eac_ruby_utils/patches/object/debug.rb
  - spec/lib/eac_ruby_utils/patches/object/if_present_spec.rb
  - spec/lib/eac_ruby_utils/patches/pathname/basename_sub_spec.rb
  - spec/lib/eac_ruby_utils/yaml_spec.rb
