require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Rails/DynamicFindBy:
  Enabled: false

Rails/Output:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/TimeZone:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Exclude:
    - spec/lib/eac_ruby_utils/patches/module/simple_cache_spec.rb
    - spec/lib/eac_ruby_utils/require_sub_spec.rb
    - spec/lib/eac_ruby_utils/settings_provider_spec.rb

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false
